name: Send Telegram Message

on:
  schedule:
    - cron: '0 1 * * 1'  # UTC 기준으로 월요일 오전 1시 (KST 기준으로 월요일 오전 10시)
  workflow_dispatch:
    inputs:
      job:
        description: 'Select job to run'
        required: true
        default: 'all'
        type: choice
        options:
          - all
          - TEST_solution

jobs:
  send_message:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.10'  # 사용할 Python 버전

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install python-telegram-bot

    - name: Run the script
      env:
        BOT_TOKEN: ${{ secrets.BOT_TOKEN }}  # GitHub Secrets에 저장된 봇 토큰
        CHAT_ID: ${{ secrets.CHAT_ID }}      # GitHub Secrets에 저장된 채팅 ID
      run: |
        python TEST_solution.py  # your_script.py를 실제 스크립트 파일명으로 변경하세요.
